name: Publishing Docs to Github Pages

on:
  push:
    branches: 
      - 'docz-dev'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Checking out the docz-dev branch
      uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install
    - name: Build Project
      run: npm run make
      run: npm run build
    - name: Deploying to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        build_dir: .docz/dist
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}  